version: '3.4'

services:
  socialnetwork.api:
    build:
      context: .
      dockerfile: SocialNetwork.API/Dockerfile
    container_name: app.api
    networks:
      - default
      - sqlserver_network
    ports:
      - 9999:9999
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx.api
    ports:
      - 1111:1111
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy.conf:/etc/nginx/proxy.conf:ro
networks:
  sqlserver_network:
    external:
      name: web_default