version: '3.4'

services:
  facebook_api:
    build:
      context: .
      dockerfile: ./SocialNetwork.API/Dockerfile
    ports:
      - 9999:9999
    restart: always
    image: duonga6/facebook.api 

  nginx:
    image: nginx:latest
    ports:
      - 1111:1111
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy.conf:/etc/nginx/proxy.conf:ro
  
