version: '3.4'

services:
  facebook_api:
    build:
      context: .
      dockerfile: ./SocialNetwork.API/Dockerfile
    ports:
      - 9999:9999
    restart: always
    image: duonga6/facebook.api
    container_name: facebook.api
    networks:
      - facebookapi-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: duonga6/nginx-facebook.api
    container_name: nginx-facebook.api
    ports:
      - 1111:1111
    networks:
      - facebookapi-network
networks:
  facebookapi-network:
    external: true
