version: '3.4'

services:
  socialnetwork.api:
    build:
      context: .
      dockerfile: SocialNetwork.API/Dockerfile
    container_name: socialnetwork.api
    networks:
      - deployment_network
    ports:
      - 9999:9999
    restart: always
networks:
  deployment_network:
    external: true
