version: '3.4'

services:
  facebook.api:
    build:
      context: .
      dockerfile: SocialNetwork.API/Dockerfile
    container_name: facebook.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 9999:9999
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx_facebook.api
    ports:
      - 1111:1111
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy.conf:/etc/nginx/proxy.conf:ro
