name: CI_Docker

on: 
  push: 
    branches: 
      - master

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create network deployment
        run: |
          docker network create deployment_network
          
      - name: Build with compose
        run: |
          docker-compose up -d
      
      - name: Add tag
        run: |
          docker tag socialnetwork.api ${{ secrets.DOCKER_USERNAME }}/socialnetwork.api

      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/socialnetwork.api

      - name: Test container
        run: |
          docker ps -a
